version: '3.3'
services:
    dev-db:
        image: mongo:latest
        ports:
            - 27027:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - oxyce_net
networks:
    oxyce_net:
